@startuml TrumpTweetStats

package de.fhro.inf.prg3.a13.tweets {
        +class TrumpTweetStats {
                +{static}calculateSourceAppStats(tweetStream: Stream<Tweet>): Map<String, Long>
                +{static}calculateTweetsBySourceApp(tweetStream: Stream<Tweet>): Map<String, Set<Tweet>>
                +{static}calculateWordCount(tweetStream: Stream<Tweet>, stopWords: List<String>): Map<String, Integer>
        }
}

@enduml